apiVersion: v1
kind: Service
metadata:
  name: notification-worker
  namespace: crs-lab
spec:
  selector:
    app: notification-worker
  ports:
    - name: http
      port: 8100
      targetPort: 8100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  namespace: crs-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8100"
        prometheus.io/path: /metrics
    spec:
      containers:
        - name: notification-worker
          image: crs-sre-lab/notification-worker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8100
          env:
            - name: SERVICE_NAME
              value: notification-worker
            - name: PORT
              value: "8100"
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: crs-app-config
                  key: REDIS_URL
            - name: RESERVATION_STREAM
              valueFrom:
                configMapKeyRef:
                  name: crs-app-config
                  key: RESERVATION_STREAM
            - name: RESERVATION_GROUP
              valueFrom:
                configMapKeyRef:
                  name: crs-app-config
                  key: RESERVATION_GROUP
            - name: PMS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: crs-app-config
                  key: PMS_BASE_URL
            - name: MAX_DELIVERY_ATTEMPTS
              valueFrom:
                configMapKeyRef:
                  name: crs-app-config
                  key: MAX_DELIVERY_ATTEMPTS
            - name: DLQ_STREAM
              valueFrom:
                configMapKeyRef:
                  name: crs-app-config
                  key: DLQ_STREAM
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8100
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8100
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 150m
              memory: 192Mi
            limits:
              cpu: 750m
              memory: 384Mi

